# Generated by Django 4.1.4 on 2022-12-12 09:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('owner_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('email_address', models.EmailField(max_length=300)),
                ('contact_no', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\d{10}')])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('industrytype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='industryapp.industrytype')),
            ],
        ),
    ]
